This PR enhances the catalog schema with commented class descriptions.
meshery/schemas pull request #83
Opened 2024-06-27 08:27 UTC by leecalcote

**Notes for Reviewers**

This PR fixes a UX issue in Cloud Catalog.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-06-27 13:17 UTC, Yashsharma1911 requested changes

2024-06-27 13:17 UTC, Yashsharma1911 commented on schemas/constructs/v1alpha1/catalog_data.json
> +                "verified", // $comment: Content produced by partners and verified by Meshery maintainers. While not directly maintained by Meshery, it has undergone a verification process to ensure
Adding description in this way will make JSON schema invalid, there are two ways to give description for enums, 1) define enum as oneOf and then use description property 2) add the [enumDescription](https://github.com/Microsoft/vscode/wiki/Setting-Descriptions) field to describe them

```
        "class": {
            "description": "Published content is classified by its support level. Content classes help you understand the origin and expected support level for each piece of content. It is important to note that the level of support may vary within each class, and you should exercise discretion when using community-contributed content.",
            "type": "string",
            "enum": [
                "official",
                "verified",
                "project",
                "community"
            ],
            "enumDescriptions": [
                "Content produced and fully supported by Meshery maintainers. This represents the highest level of support and is considered the most reliable.",
                "Content produced by partners and verified by Meshery maintainers. While not directly maintained by Meshery, it has undergone a verification process to ensure quality and compatibility.",
                "Content produced and supported by the respective project or organization responsible for the specific technology. This class offers a level of support from the project maintainers themselves.",
                "Content produced and shared by Meshery users. This includes a wide range of content, such as performance profiles, test results, filters, patterns, and applications. Community content may have varying levels of support and reliability."
            ]
        }
```

I think using oneOf can be major change and we don't need that, so I propose that we should use the second approach

2024-06-27 13:18 UTC, Yashsharma1911 commented on schemas/constructs/v1alpha1/catalog_data.json
> +                "verified", // $comment: Content produced by partners and verified by Meshery maintainers. While not directly maintained by Meshery, it has undergone a verification process to ensure
@aabidsofi19 what do you think?

2024-06-27 13:24 UTC, aabidsofi19 commented on schemas/constructs/v1alpha1/catalog_data.json
> +                "verified", // $comment: Content produced by partners and verified by Meshery maintainers. While not directly maintained by Meshery, it has undergone a verification process to ensure
makes sense  to me , we would need to  enhance the classes endpoint to return these also

2024-06-28 10:19 UTC, Yashsharma1911 approved these changes

2024-06-28 10:19 UTC, merged